# ========================================
# Parameters 1
# ========================================
# gcn_conv1_hid : 256
# gcn_conv2_out : 128
# egnn_emb_in : 128
# egnn_emb_hid : 32
# egnn_emb_out : 16
# egnn_n_layers : 4
# proto_in : 16
# proto_hid : 128
# proto_out : 16

# ========================================
# Parameters 2
# ========================================
# gcn_conv1_hid : 64
# gcn_conv2_out : 16
# egnn_emb_in : 16
# egnn_emb_hid : 8
# egnn_emb_out : 4
# egnn_n_layers : 4
# proto_in : 4
# proto_hid : 128
# proto_out : 4

# ========================================
# Parameters 3
# ========================================
# gcn_conv1_hid : 32
# gcn_conv2_out : 32
# egnn_emb_in : 32
# egnn_emb_hid : 128
# egnn_emb_out : 32
# egnn_n_layers : 4
# proto_in : 32
# proto_hid : 128
# proto_out : 32

# ========================================
# Parameters 4
# ========================================
# gcn_conv1_hid : 32
# gcn_conv2_out : 32
# egnn_emb_in : 32
# egnn_emb_hid : 128
# egnn_emb_out : 32
# egnn_n_layers : 3
# proto_in : 32
# proto_hid : 128
# proto_out : 32
# pgcl_hid : 128

# ========================================
# Parameters 5 Amazon_Clothing 
# ========================================
# gcn_conv1_hid : 37
# gcn_conv2_out : 32
# egnn_emb_in : 32
# egnn_emb_hid : 128
# egnn_emb_out : 32
# egnn_n_layers : 3
# proto_in : 32
# proto_hid : 512
# proto_out : 32
# pgcl_hid : 512

# ========================================
# Parameters 6 Amazon_Clothing 
# ========================================
gcn_conv1_hid : 37
gcn_conv2_out : 32
egnn_emb_in : 32
egnn_emb_hid : 128
egnn_emb_out : 32
egnn_n_layers : 3
proto_in : 32
proto_hid : 512
proto_out : 32
pgcl_hid : 512